### ISSUE TITLE
接金子游戏有时向左移动会卡住

### ISSUE THREAD

**Issue by kent666a** [chenyinkai/egret-games#2]
接金子游戏有时向左移动会卡住，重现多次，应该是bug

**Comment by kent666a** [comment]
完全在篮子上面应该没问题，应该是我操作鼠标移出了篮子，或许将范围调大一些体验会更好

**Comment by chenyinkai** [comment]
@kent124454731 是的，现在的事件都是添加到篮子上面，鼠标超出篮子了，就没有拖拽的效果了。

**Comment by chenyinkai** [comment]
@kent124454731 pc上的话这种一般是靠方向键移动的，手机上的话重力感应体验更好，，因为也是自己写着玩的，所以没有考虑这么多，，用鼠标拖拽体验是不太好，，主要范围加大了，那没有点到篮子，篮子也能动，额，这样感觉也不合适。。

**Comment by kent666a** [comment]
也是，我还没在手机上试。还是做得很不错的。 @chenyinkai

**Comment by chenyinkai** [comment]
哈哈，谢谢，我也是这几天又开始用egret，所以随便上传了下，没想到还真的有人看。。额额，有些吃惊。 @kent124454731

**Comment by kent666a** [comment]
@chenyinkai 我也是这几天看，刚开始使用就能做这样，好厉害啊。貌似egret最新版的wing有好多bug

**Comment by chenyinkai** [comment]
@kent124454731 没有，我之前就看过一段时间，那时候引擎版本还是3.2，，因为刚好需要做一个游戏，就又开始看egret了，wing我暂时还没遇到什么大问题诶。。。哈哈，一起学习。。

**Comment by kent666a** [comment]
@chenyinkai 嗯嗯，一起学习，你更新下wing看看exml还能不能正常拖控件

**Comment by chenyinkai** [comment]
@kent124454731 额，eui我都还没用过。。。
